@startuml
class Constantes.Constante
class Utilities.Utils
class java.awt.Color
class java.awt.Dimension
class java.awt.Point
Constantes.Constante ..> Utilities.Utils
Constantes.Constante ..> java.awt.Color
Constantes.Constante ..> java.awt.Dimension
Constantes.Constante ..> java.awt.Point
@enduml