@startuml
annotation java.lang.Override
annotation java.lang.SuppressWarnings
class Constantes.Constante
class Gui.Drawer
class PacObject.PacMan
class Utilities.Direction
class java.awt.Color
class java.awt.Graphics
class java.awt.Graphics2D
class java.awt.Point
class java.awt.Polygon
class javax.swing.JPanel
Gui.Drawer ..> java.lang.Override
Gui.Drawer ..> java.lang.SuppressWarnings
Gui.Drawer ..> Constantes.Constante
Gui.Drawer ..> PacObject.PacMan
Gui.Drawer ..> Utilities.Direction
Gui.Drawer ..> java.awt.Color
Gui.Drawer ..> java.awt.Graphics
Gui.Drawer ..> java.awt.Graphics2D
Gui.Drawer ..> java.awt.Point
Gui.Drawer ..> java.awt.Polygon
Gui.Drawer --|> javax.swing.JPanel
@enduml