@startuml
annotation java.lang.Override
annotation java.lang.SuppressWarnings
class Constantes.Constante
class Gui.Block
class Gui.Drawer
class Gui.Maze
class Gui.Structure
class Gui.Transformers
class Gui.Transformers.Mapper
class PacObject.PacGhost
class PacObject.PacMan
class Utilities.Direction
class Utilities.Utils
class java.awt.BorderLayout
class java.awt.Color
class java.awt.Dimension
class java.awt.Graphics
class java.awt.Graphics2D
class java.awt.Point
class java.awt.Polygon
class java.awt.event.KeyListener
class java.util.ArrayList
class java.util.List
class javax.swing.JFrame
class javax.swing.JLabel
class javax.swing.JPanel
enum Gui.Lines
Gui.Block ..> java.awt.Color
Gui.Block ..> java.awt.Point
Gui.Drawer ..> java.lang.Override
Gui.Drawer ..> java.lang.SuppressWarnings
Gui.Drawer ..> Constantes.Constante
Gui.Drawer ..> PacObject.PacMan
Gui.Drawer ..> Utilities.Direction
Gui.Drawer ..> java.awt.Color
Gui.Drawer ..> java.awt.Graphics
Gui.Drawer ..> java.awt.Graphics2D
Gui.Drawer ..> java.awt.Point
Gui.Drawer ..> java.awt.Polygon
Gui.Drawer --|> javax.swing.JPanel
Gui.Maze ..> Constantes.Constante
Gui.Maze ..> PacObject.PacGhost
Gui.Maze ..> PacObject.PacMan
Gui.Maze ..> Utilities.Utils
Gui.Maze ..> java.awt.BorderLayout
Gui.Maze ..> java.awt.Dimension
Gui.Maze ..> java.awt.event.KeyListener
Gui.Maze ..> javax.swing.JFrame
Gui.Maze ..> javax.swing.JLabel
Gui.Maze ..> javax.swing.JPanel
Gui.Structure ..> Constantes.Constante
Gui.Structure ..> Gui.Transformers.Mapper
Gui.Structure ..> java.awt.Color
Gui.Structure ..> java.awt.Graphics
Gui.Structure ..> java.awt.Point
Gui.Structure ..> java.util.ArrayList
Gui.Structure ..> java.util.List
Gui.Transformers ..> java.util.ArrayList
Gui.Transformers ..> java.util.List
@enduml