@startuml
class Constantes.Constante
class Gui.Maze
class PacObject.PacGhost
class PacObject.PacMan
class Utilities.Utils
class java.awt.BorderLayout
class java.awt.Dimension
class java.awt.event.KeyListener
class javax.swing.JFrame
class javax.swing.JLabel
class javax.swing.JPanel
Gui.Maze ..> Constantes.Constante
Gui.Maze ..> PacObject.PacGhost
Gui.Maze ..> PacObject.PacMan
Gui.Maze ..> Utilities.Utils
Gui.Maze ..> java.awt.BorderLayout
Gui.Maze ..> java.awt.Dimension
Gui.Maze ..> java.awt.event.KeyListener
Gui.Maze ..> javax.swing.JFrame
Gui.Maze ..> javax.swing.JLabel
Gui.Maze ..> javax.swing.JPanel
@enduml