@startuml
class Constantes.Constante
class Gui.Structure
class Gui.Transformers.Mapper
class java.awt.Color
class java.awt.Graphics
class java.awt.Point
class java.util.ArrayList
class java.util.List
Gui.Structure ..> Constantes.Constante
Gui.Structure ..> Gui.Transformers.Mapper
Gui.Structure ..> java.awt.Color
Gui.Structure ..> java.awt.Graphics
Gui.Structure ..> java.awt.Point
Gui.Structure ..> java.util.ArrayList
Gui.Structure ..> java.util.List
@enduml